### ISSUE TITLE
Functor (<$>) has wrong signature

### ISSUE THREAD

**Issue by arkadiuszbicz** [haskell/haskell-wiki-configuration#19]
Functor (<$>) has wrong signature on page https://wiki.haskell.org/Functor. 

Is in 2 Syntax section : 

(<$>) :: a -> f b -> f a 

Should be:

(<$>) :: (a -> b) -> f a -> f b

**Comment by hgolden** [comment]
Thank you for pointing out the error. Since this is a wiki, you can make
the correction yourself. If you don't have an account yet, please request
one, so you can make changes.

Note: The error in section 2 of the wiki page is that it defines (<$>),
when it should define (<$). You can see this by looking at the definition
of Data.Functor (see
https://hackage.haskell.org/package/base-4.7.0.2/docs/src/GHC-Base.html#Functor).
A previous edit to section 2 of the wiki page incorrectly replaced (<$)
with (<$>). So the proper correction in section 2 is to revert (<$>) back
to (<$).
