### ISSUE TITLE
Planning for upgrade to MediaWiki 1.35.2 (LTS)

### ISSUE THREAD

**Issue by hgolden** [haskell/haskell-wiki-configuration#20]
We have just upgraded the Haskell wiki's MediaWiki version to 1.27.4 (LTS). However, support for this version ends in June 2019 (see [MediaWiki's version lifecycle](https://www.mediawiki.org/wiki/Version_lifecycle)). I recommend that we plan to upgrade to MediaWiki 1.31.x (LTS) by the end of June 2019 or as soon as possible thereafter. Version 1.31.x will be supported until June 2021.

I will try out the 1.31.x version on my own computer and see how much work it will be to upgrade to it.

Please comment on this upgrade recommendation, and also reply if you would like to be involved in the upgrade.

**Comment by hgolden** [comment]
I have been able to upgrade the Haskell wiki to MediaWiki version 1.31.x (LTS) on my own computer. There was one major snag (see https://www.mediawiki.org/wiki/Topic:Uf63mplrzzuxz0it) which caused a misleading error message that had me puzzled for a couple of days. Other than that, version 1.31.x seems to work fine. (Note: My computer isn't accessible from the Internet (I hope), so I should probably set up a visible staging server to allow for others to try it out. Please help me get one I can use for this.)

**Comment by gbaz** [comment]
Sorry howard I don't have staging servers really lying around anymore now
that we're moving on from rackspace. The boxes we use now are physical
(though still on demand). If you're confident in the upgrade and have
everything backed up, I say we just go for it :-)

Cheers,
Gershom

(btw, I'm powering down the old staging instance that you had way back on
rackspace, since I think it is no longer relevant. Let me know if any
issues arise because of this)

**Comment by hgolden** [comment]
Gershom,

I want to do some more testing first. I’ll let you know when I’m ready. 

Howard

**Comment by hgolden** [comment]
Now I'm in process of implementing a dockerized version of MediaWiki-1.35.2.

**Comment by hgolden** [comment]
This task was completed before, but now I'm closing it.
