### ISSUE TITLE
Add syntax highlighting for .cabal files

### ISSUE THREAD

**Issue by nattybear** [haskell/haskell-wiki-configuration#42]
Currently, the Haskell Wiki lacks syntax highlighting support for `.cabal` files, which are crucial for managing Haskell projects. Adding syntax highlighting for these files would greatly benefit developers working with Haskell.

**Comment by hgolden** [comment]
@nattybear , since the Haskell wiki is based on Mediawiki, you can syntax highlight any  language supported by [Pygments](https://github.com/pygments/pygments). However, I don't see that there is a grammar for `.cabal` files. Perhaps someone working on the Cabal project can provide you one or help you to add one to Pygments.

**Comment by nattybear** [comment]
I just use syntax highlighting for yaml like below:

```
<syntaxhighlight lang=yaml>
...
</syntaxhighlight>
```

**Comment by hgolden** [comment]
Is the YAML syntax highlighting sufficient for your needs? If so, I
will close this.

**Comment by nattybear** [comment]
Yes, please close it.
