### ISSUE TITLE
Sorry! This site is experiencing technical difficulties.

### ISSUE THREAD

**Issue by palfrey** [haskell/haskell-wiki-configuration#43]
On all pages AFAIK, for several days at least

**Comment by hgolden** [comment]
Hi Tom,I am responsible for causing the problem due to an error I made while trying to update the wiki’s server and all of its software. I am terribly sorry and I apologize to you and all who want to use the wiki! Mea culpa!We (haskell.org infrastructure) are working hard to correct the problems! I can’t offer an ETA yet, but a lot of people are involved in helping to fix this promptly. Regards,HowardOn Nov 13, 2024, at 1:24 PM, Tom Parker-Shemilt ***@***.***> wrote:﻿
On all pages AFAIK, for several days at least

**Comment by simonmichael** [comment]
Thanks for your work @hgolden ! It happens.

**Comment by hgolden** [comment]
The site is back up, but there may still be some problems. Please report here any problems you find that haven't been reported already.
